#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, and for the 9th iteration, it displays "Best School" and then "Hi"

i=1
while [ $i -le 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((i++))
done
