#!/usr/bin/env bash
# This script displays hours from 0 to 12 and minutes from 0 to 59 using a while loop

hour=0
while [ $hour -le 12 ]
do
  minute=0
  while [ $minute -le 59 ]
  do
    echo "$hour:$minute"
    ((minute++))
  done
  ((hour++))
done
